feat(@videndum/release-mastermind)!: staleness, schedules and more
Videndum/smartcloud pull request #203
Opened 2021-08-05 21:45 UTC by TGTGamer

# Name your pull request here

## References

## Author's checklist

- [ ] Code has passed all

2021-08-05 21:46 UTC, VidendumStudios requested changes, later dismissed
<!--releaseMastermind: Conventions-->

Semantic Conditions failed - Please title your pull request using one of the valid options:

 Types: bug, chore, opt, optimisation, style, maint, maintenance, ref, refactor, revert, dep, deprecated, removal, docs, documentation, feat, enhance, feature, enhancement, fix

 Contexts: @videndum/workflow-mastermind, @videndum/release-mastermind, @videndum/label-mastermind, @videndum/variable-mastermind, @videndum/convention-mastermind, condition, api, util, installer, deps, deps-dev

----------

This message will be automatically updated when you make this change

2021-08-05 21:52 UTC, TGTGamer commented on packages/release-mastermind/src/contexts/schedule.ts
> +import { LoggingDataClass, LoggingLevels } from "@videndum/utilities";
Codacy has a fix for the issue: [There should be no space after '{'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {LoggingDataClass, LoggingLevels } from "@videndum/utilities";
```

2021-08-05 21:52 UTC, TGTGamer commented on packages/release-mastermind/src/conditions/util/isStale.ts
> +  type: typeof TYPE;
Codacy has a fix for the issue: [A readonly modifier is required.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  readonly type: typeof TYPE;
```

2021-08-05 21:52 UTC, TGTGamer commented on packages/release-mastermind/src/conditions/util/isAbandoned.ts
> +  if (!issue.lastUpdated || !issue.labels?.[condition.label.toLowerCase()])
Codacy has a fix for the issue: [Unexpected nullable string value in conditional. Please handle the nullish/empty cases explicitly.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  if ((issue.lastUpdated == null) || !issue.labels?.[condition.label.toLowerCase()])
```

2021-08-05 21:52 UTC, TGTGamer commented on packages/release-mastermind/src/utils/helper/semantic.ts
> +  "fix",
Codacy has a fix for the issue: [Unexpected trailing comma.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  "fix"
```

2021-08-05 21:52 UTC, TGTGamer commented on packages/release-mastermind/src/contexts/methods/checkStale.ts
> +import { LoggingLevels } from "@videndum/utilities";
Codacy has a fix for the issue: [There should be no space after '{'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {LoggingLevels } from "@videndum/utilities";
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/src/contexts/schedule.ts
> +import { Context } from "@actions/github/lib/context";
Codacy has a fix for the issue: [There should be no space after '{'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {Context } from "@actions/github/lib/context";
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +  ScheduleCondition
Codacy has a fix for the issue: [Insert `,`](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  ScheduleCondition,
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/src/conditions/util/isAbandoned.ts
> +import { UtilProps, UtilThis } from "..";
Codacy has a fix for the issue: [The variable `UtilProps` should be named `UtilProperties`. A more descriptive name will do too.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import { UtilProps as UtilProperties, UtilThis } from "..";
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/src/utils/parsingData.ts
> +import { Label, Labels } from "../../types";
Codacy has a fix for the issue: [There should be no space after '{'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {Label, Labels } from "../../types";
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +import { Repo } from '../src/utils'
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import { Repo } from "../src/utils"
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +} from '../src/conditions'
Codacy has a fix for the issue: [Replace `'../src/conditions'` with `"../src/conditions";`](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
} from "../src/conditions";
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/src/contexts/methods/checkStale.ts
> +import { Issues, Project, PullRequests, Schedule } from "..";
Codacy has a fix for the issue: [There should be no space after '{'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {Issues, Project, PullRequests, Schedule } from "..";
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +} from '../src/conditions'
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
} from "../src/conditions"
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/src/contexts/methods/checkStale.ts
> +import { UtilThis } from "../../conditions";
Codacy has a fix for the issue: [There should be no space after '{'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {UtilThis } from "../../conditions";
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/src/conditions/util/isStale.ts
> +  value: number;
Codacy has a fix for the issue: [A readonly modifier is required.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  readonly value: number;
```

2021-08-05 22:03 UTC, TGTGamer commented on packages/release-mastermind/src/contexts/methods/checkStale.ts
> +import { AbanondedConfig, StaleConfig } from "../../../types";
Codacy has a fix for the issue: [There should be no space after '{'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {AbanondedConfig, StaleConfig } from "../../../types";
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +  [key: string]: Label
Codacy has a fix for the issue: [Expected a semicolon.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  [key: string]: Label;
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/src/action.ts
> +          `Error thrown while running context: `,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
          "Error thrown while running context: ",
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/src/contexts/methods/checkStale.ts
> +        : undefined,
Codacy has a fix for the issue: [':' should be placed at the end of the line.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
        undefined,
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +  column: string
Codacy has a fix for the issue: [Insert `;`](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  column: string;
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +    build: string
Codacy has a fix for the issue: [Insert `;`](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
    build: string;
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +  releaseNamePrefix?: string
Codacy has a fix for the issue: [Insert `;`](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  releaseNamePrefix?: string;
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +  abandoned?: AbanondedConfig
Codacy has a fix for the issue: [Expected a semicolon.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  abandoned?: AbanondedConfig;
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> + * Config types
Codacy has a fix for the issue: [Sentence must end with a period.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
 * Config types.
```

2021-08-05 22:28 UTC, TGTGamer commented on packages/release-mastermind/types/index.d.ts
> +  createBranch?: { [label: string]: CreateBranch }
Codacy has a fix for the issue: [Expected a semicolon.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
  createBranch?: { [label: string]: CreateBranch };
```

2021-08-06 00:15 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/methods/applyLabels.ts
> +			delete this.context.props.labels[labelName.toLowerCase()]
Codacy has a fix for the issue: [Expected { after 'if' condition.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      {delete this.context.props.labels[labelName.toLowerCase()]}
```

2021-08-06 01:15 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/methods/checkStale.ts
> +			if (!config.abandoned.requires) config.abandoned.requires = 1
Codacy has a fix for the issue: [Expected { after 'if' condition.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      if (!config.abandoned.requires) {config.abandoned.requires = 1}
```

2021-08-06 01:15 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/methods/checkStale.ts
> +			else config.abandoned.requires++
Codacy has a fix for the issue: [Expected { after 'else'.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      else {config.abandoned.requires++}
```

2021-08-08 06:12 UTC, madalenamelo commented on packages/release-mastermind/src/utils/labels.ts
> +		throw log(LoggingLevels.error, `Error thrown while getting labels: ` + err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
    throw log(LoggingLevels.error, "Error thrown while getting labels: " + err)
```

2021-08-08 06:12 UTC, madalenamelo commented on packages/release-mastermind/src/contexts/pullRequests.ts
> +			log(LoggingLevels.error, `Error thrown while parsing labels: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      log(LoggingLevels.error, "Error thrown while parsing labels: ", err)
```

2021-08-08 06:12 UTC, madalenamelo commented on packages/release-mastermind/src/action.ts
> +					`Error thrown while parsing Schedule context: `,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
            "Error thrown while parsing Schedule context: ",
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/action.ts
> +				`Error thrown while processing config: `,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
        "Error thrown while processing config: ",
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/methods/conventions.ts
> +	let prefix = `<!--releaseMastermind: Conventions-->`,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
	let prefix = "<!--releaseMastermind: Conventions-->",
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/pullRequests.ts
> +				log(LoggingLevels.error, `Error thrown while handling changes: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
        log(LoggingLevels.error, "Error thrown while handling changes: ", err)
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/pullRequests.ts
> +				log(LoggingLevels.error, `Error thrown while parsing versioning: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
        log(LoggingLevels.error, "Error thrown while parsing versioning: ", err)
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/issues.ts
> +				log(LoggingLevels.error, `Error thrown while parsing versioning: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
        log(LoggingLevels.error, "Error thrown while parsing versioning: ", err)
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/projects.ts
> +				log(LoggingLevels.error, `Error thrown while parsing versioning: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
        log(LoggingLevels.error, "Error thrown while parsing versioning: ", err)
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/action.ts
> +					`Error thrown while parsing Schedule context: `,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
            "Error thrown while parsing Schedule context: ",
```

2021-08-08 06:45 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/projects.ts
> +					`project actions failed. Terminating job.`
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
          "project actions failed. Terminating job."
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/schedule.ts
> +					`Scheduled actions failed. Terminating job.`,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
          "Scheduled actions failed. Terminating job.",
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/schedule.ts
> +						log(LoggingLevels.error, `Error thrown while parsing labels: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
            log(LoggingLevels.error, "Error thrown while parsing labels: ", err)
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/issues.ts
> +			`context.payload.issue: ` + JSON.stringify(context.payload.issue)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      "context.payload.issue: " + JSON.stringify(context.payload.issue)
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/utils/labels.ts
> +					log(LoggingLevels.error, `Error thrown while updating label: ` + err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
          log(LoggingLevels.error, "Error thrown while updating label: " + err)
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/methods/conventions.ts
> +	let prefix = `<!--releaseMastermind: Conventions-->`,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
	let prefix = "<!--releaseMastermind: Conventions-->",
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/pullRequests.ts
> +			`context.payload.pull_request: ` +
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      "context.payload.pull_request: " +
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/issues.ts
> +					`Issue actions failed. Terminating job.`
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
          "Issue actions failed. Terminating job."
```

2021-08-08 16:47 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/pullRequests.ts
> +				log(LoggingLevels.error, `Error thrown while parsing versioning: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
        log(LoggingLevels.error, "Error thrown while parsing versioning: ", err)
```

2021-08-09 03:32 UTC, VidendumStudios commented on packages/release-mastermind/src/action.ts
> +				`Error thrown while running context: `,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
          "Error thrown while running context: ",
```

2021-08-09 03:32 UTC, VidendumStudios commented on packages/release-mastermind/src/action.ts
> +					`Error thrown while parsing Schedule context: `,
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
            "Error thrown while parsing Schedule context: ",
```

2021-08-09 03:32 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/projects.ts
> +			log(LoggingLevels.error, `Error thrown while parsing labels: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      log(LoggingLevels.error, "Error thrown while parsing labels: ", err)
```

2021-08-09 03:32 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/issues.ts
> +					`Issue actions failed. Terminating job.`
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
          "Issue actions failed. Terminating job."
```

2021-08-09 03:32 UTC, VidendumStudios commented on packages/release-mastermind/src/contexts/pullRequests.ts
> +				log(LoggingLevels.error, `Error thrown while listing files: `, err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
      log(LoggingLevels.error, "Error thrown while listing files: ", err)
```

2021-08-09 03:32 UTC, VidendumStudios commented on packages/release-mastermind/src/utils/labels.ts
> +		throw log(LoggingLevels.error, `Error thrown while getting labels: ` + err)
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
    throw log(LoggingLevels.error, "Error thrown while getting labels: " + err)
```

2021-08-09 03:32 UTC, VidendumStudios commented on packages/release-mastermind/src/index.ts
> +import {getOctokit} from '@actions/github'
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Videndum/action-masterminds/pullRequest?prid=7872005)
```suggestion
import {getOctokit} from "@actions/github"
```

2021-09-11 14:26 UTC, merged